#  Copyright 2024 IBM Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Create Namespace resource (name: {{ project }})"
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ project }}"
        state: present

    - name: "Create OperatorGroup resource (name: rhods-operator)"
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        resource_definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: rhods-operator
            namespace: "{{ project }}"
        state: present

    - name: "Create Subscription resource (name: rhods-operator)"
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        resource_definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: rhods-operator
            namespace: "{{ project }}"
          spec:
            channel: "{{ channel }}"
            config:
              env:
                - name: "DISABLE_DSC_CONFIG"
            name: rhods-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
        state: present

    - name: "Waiting for creation of custom resource definitions"
      wait_for_custom_resource_definitions:
        kubeconfig: "{{ kube_config }}"
        custom_resource_definitions:
          - "DataScienceCluster"
          - "DSCInitialization"
          - "FeatureTracker"

    - name: "Create DSCInitialization resource (name: default-dsci)"
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        resource_definition:
          apiVersion: dscinitialization.opendatahub.io/v1
          kind: DSCInitialization
          metadata:
            name: default-dsci
          spec:
            applicationsNamespace: redhat-ods-applications
            monitoring:
              managementState: Managed
              namespace: redhat-ods-monitoring
            serviceMesh:
              managementState: Removed
            trustedCABundle:
              customCABundle: ""
              managementState: Managed
        state: present

    - name: "Waiting for creation and readiness of custom resource (name: default-dsci)"
      wait_for_custom_resource:
        custom_resource_name: "default-dsci"
        group: "dscinitialization.opendatahub.io"
        jmespath_expression: "object.status.phase == 'Ready'"
        kind: "DSCInitialization"
        kubeconfig: "{{ kube_config }}"
        plural: "dscinitializations"
        version: "v1"

    - name: "Create DataScienceCluster resource (name: default-dsc)"
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        resource_definition:
          apiVersion: datasciencecluster.opendatahub.io/v1
          kind: DataScienceCluster
          metadata:
            name: default-dsc
          spec:
            components:
              codeflare:
                managementState: Removed
              dashboard:
                managementState: Removed
              datasciencepipelines:
                managementState: Removed
              kserve:
                defaultDeploymentMode: RawDeployment
                managementState: Managed
                serving:
                  managementState: Removed
                  name: knative-serving
              kueue:
                managementState: Removed
              modelmeshserving:
                managementState: Removed
              ray:
                managementState: Removed
              trainingoperator:
                managementState: Managed
              trustyai:
                managementState: Removed
              workbenches:
                managementState: Removed

    - name: "Waiting for creation and readiness of custom resource (name: default-dsc)"
      wait_for_custom_resource:
        custom_resource_name: "default-dsc"
        group: "datasciencecluster.opendatahub.io"
        jmespath_expression: "object.status.phase == 'Ready'"
        kind: "DataScienceCluster"
        kubeconfig: "{{ kube_config }}"
        plural: "datascienceclusters"
        version: "v1"

    - name: "Get channel"
      kubernetes.core.k8s_info:
        kind: ConfigMap
        kubeconfig: "{{ kube_config }}"
        name: inferenceservice-config
        namespace: redhat-ods-applications
      register: k8s_info_result

    - set_fact:
        ingress: '{{ k8s_info_result | json_query(''resources[0].data.ingress'') | replace(''"domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}"'', ''"domainTemplate": "example.com"'') }}'

    - name: "Patch ConfigMap resource (name: inferenceservice-config)"
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        resource_definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            annotations:
              opendatahub.io/managed: "false"
            name: inferenceservice-config
            namespace: redhat-ods-applications
          data:
            ingress: "{{ ingress }}"
