name: PyPI/Quay

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: ${{ github.event.base_ref == 'refs/heads/master' }}
    name: Build Python 🐍 distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # https://github.com/actions/checkout
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        # https://github.com/actions/setup-python
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build wheel
        run: >-
          python -m
          build
      - uses: actions/upload-artifact@v3
        # https://github.com/actions/upload-artifact
        with:
          name: workspace
          path: |
            dist
            Dockerfile
  pypi:
    name: Publish distribution 📦 to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        # https://github.com/actions/download-artifact
        with:
          name: workspace
      - uses: pypa/gh-action-pypi-publish@release/v1
        # https://github.com/pypa/gh-action-pypi-publish
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
  docker:
    name: Build and publish Docker image 🐳
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        # https://github.com/actions/download-artifact
        with:
          name: workspace
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        # https://github.com/docker/metadata-action
        with:
          images: |
            quay.io/ibm/cloud-pak-operations-cli
          tags: |
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-qemu-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # https://github.com/docker/setup-buildx-action
      - name: Log in to Quay Container Registry
        uses: docker/login-action@v1
        # https://github.com/docker/login-action
        with:
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
      - name: Build and push
        uses: docker/build-push-action@v2
        # https://github.com/docker/build-push-action
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  release:
    name: Create GitHub release
    needs: [docker, pypi]
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        # https://github.com/softprops/action-gh-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
